using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Mentor.UI.Bwoink;

[GenerateTypedNameReferences]
public sealed partial class MentorBwoinkWindow : DefaultWindow
{
    public MentorBwoinkWindow()
    {
        RobustXamlLoader.Load(this);
        
        SendButton.OnPressed += _ => SendMessage();
        CloseButton.OnPressed += _ => Close();
    }

    private void SendMessage()
    {
        if (string.IsNullOrWhiteSpace(MessageInput.Text))
            return;

        var message = MessageInput.Text;
        MessageInput.Text = string.Empty;
        
        // TODO: Send message to server
        MessageHistory.Text += $"\nYou: {message}";
    }

    public void ReceiveMessage(string message)
    {
        MessageHistory.Text += $"\n{message}";
    }
} 