using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Mentor.UI;

[GenerateTypedNameReferences]
public sealed partial class MentorWindow : DefaultWindow
{
    public MentorWindow()
    {
        RobustXamlLoader.Load(this);
    }
} 