using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Mentor.UI;

[GenerateTypedNameReferences]
public sealed partial class MhelpPanel : Control
{
    public MhelpPanel()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddTicket(int ticketId, string text)
    {
        var entry = new TicketEntry(ticketId, text);
        TicketList.AddTicket(entry);
    }

    public void ClearTickets()
    {
        TicketList.ClearTickets();
    }
} 