using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Mentor.UI;

[GenerateTypedNameReferences]
public sealed partial class MhelpControl : Control
{
    public event Action<string, string>? OnSubmit;

    public MhelpControl()
    {
        RobustXamlLoader.Load(this);
        SubmitButton.OnPressed += _ => Submit();
    }

    private void Submit()
    {
        if (string.IsNullOrWhiteSpace(TitleInput.Text) || string.IsNullOrWhiteSpace(DescriptionInput.Text))
            return;

        OnSubmit?.Invoke(TitleInput.Text, DescriptionInput.Text);
        TitleInput.Text = string.Empty;
        DescriptionInput.Text = string.Empty;
    }
} 