using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Mentor.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketListControl : Control
{
    public TicketListControl()
    {
        RobustXamlLoader.Load(this);
    }

    public void AddTicket(TicketEntry ticket)
    {
        TicketList.Children.Add(ticket);
    }

    public void ClearTickets()
    {
        TicketList.Children.Clear();
    }
} 