using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Sunrise.Mentor.UI;

[GenerateTypedNameReferences]
public sealed partial class TicketEntry : Control
{
    public int TicketId { get; }

    public TicketEntry(int ticketId, string text)
    {
        RobustXamlLoader.Load(this);
        TicketId = ticketId;
        TicketText.Text = text;
    }
} 